# Setup

In [50]:
# third party packages
import numpy as np 

In [51]:
np.__version__

'1.20.3'

# Explanation 
It can be effective to show how the change in a single variable changes the prediction of a model. In multiple regression it is necessary to hold all other variables constant in order to show the impact of a single variable. 

This can be expressed as "All things the same, . . . " in plain english

# Tutorial

## Create a range of the values for your target variable

In [41]:
# np.arange is inclusive of the lowest value
# so the lowest value you want in your simulated range in your lower bound
lowest_value = 0
lower_bound = lowest_value

In [42]:
# np.arange is exclusive of the highest value, 
# so your want your upper bound to be one spacing interval(or less) higher 
# than highest value you want in your simulated range
highest_value = 10
spacing_interval = 1
upper_bound = highest_value + spacing_interval

In [43]:
#create the vector of simulated data for your target variable
target_variable_vector = np.arange(lower_bound, upper_bound, spacing_interval)

target_variable_vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Create a vector (or vectors) of equal length for the other variables in your model

In [52]:
# get the length of the range of values for your target variable vector
n = len(target_variable_vector)

# the other variables are being held constant
# so the entire vector will be the same value for all data points
other_variable_value = 2
other_variable_vector = np.repeat(other_variable_value, n)

other_variable_vector

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Combine them together in a matrix and feed it to the predict function of your model

In [46]:
simulated_data_matrix = np.column_stack((target_variable_vector, other_variable_vector))

simulated_data_matrix

array([[ 0,  2],
       [ 1,  2],
       [ 2,  2],
       [ 3,  2],
       [ 4,  2],
       [ 5,  2],
       [ 6,  2],
       [ 7,  2],
       [ 8,  2],
       [ 9,  2],
       [10,  2]])

# Links to Functions Used:
- np.arange()
    - https://numpy.org/doc/stable/reference/generated/numpy.arange.html
    
- np.repeat()
    - https://numpy.org/doc/stable/reference/generated/numpy.repeat.html
    
- np.column_stack()
    - https://numpy.org/doc/stable/reference/generated/numpy.column_stack.html